# -*- coding: utf-8 -*-
"""TP3 - UNet Brain Tumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqUaiyb85RBv69WT3QJZuBHsWcebsQva

# Segmentación de tumores cerebrales con U-Net

**Dataset:** [LGG MRI Segmentation](https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation)  
**Tarea:** Segmentación semántica binaria (tumor / no tumor) sobre imágenes de resonancia magnética cerebral.

## Estructura
1. Setup y descarga del dataset
2. Exploración del dataset
3. Preprocesamiento
4. Dataset y DataLoaders
5. Arquitectura U-Net
6. Entrenamiento
7. Evaluación y resultados

## 1. Setup y descarga del dataset

Para descargar el dataset desde Kaggle en Colab necesitás subir tu archivo `kaggle.json`.
"""

# Instalar dependencias necesarias
!pip install -q kaggle segmentation-models-pytorch

import os
from google.colab import files

# Cuando aparezca el selector de archivos, elegí kaggle.json
uploaded = files.upload()

os.makedirs('/root/.kaggle', exist_ok=True)
with open('/root/.kaggle/kaggle.json', 'wb') as f:
    f.write(uploaded[list(uploaded.keys())[0]])
os.chmod('/root/.kaggle/kaggle.json', 0o600)
print('kaggle.json configurado correctamente.')

!kaggle datasets download -d mateuszbuda/lgg-mri-segmentation -p /content/data --unzip
!ls /content/data/

"""## 2. Exploración del dataset

El dataset contiene imágenes `.tif` de MRI cerebral y sus máscaras correspondientes.  
Cada paciente tiene su propio directorio. Las máscaras se identifican con el sufijo `_mask.tif`.
"""

import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

DATA_DIR = '/content/data/kaggle_3m'

# Construir lista de pares (imagen, máscara)
image_paths = sorted(glob.glob(os.path.join(DATA_DIR, '**', '*.tif'), recursive=True))
image_paths = [p for p in image_paths if '_mask' not in p]
mask_paths  = [p.replace('.tif', '_mask.tif') for p in image_paths]

# Verificar que existen todas las máscaras
assert all(os.path.exists(m) for m in mask_paths), 'Hay imágenes sin máscara'

print(f'Total de pares imagen-máscara: {len(image_paths)}')

# Estadísticas del dataset
positive = sum(1 for m in mask_paths if np.array(Image.open(m)).max() > 0)
negative = len(mask_paths) - positive

print(f'Imágenes con tumor (máscara no vacía): {positive} ({100*positive/len(mask_paths):.1f}%)')
print(f'Imágenes sin tumor (máscara vacía):    {negative} ({100*negative/len(mask_paths):.1f}%)')

# Tamaño de muestra
sample_img = np.array(Image.open(image_paths[0]))
print(f'\nDimensiones de imagen de ejemplo: {sample_img.shape}, dtype: {sample_img.dtype}')

# Visualizar muestras: imagen original + máscara + superposición
def show_sample(img_path, mask_path, ax_row):
    img  = np.array(Image.open(img_path).convert('RGB'))
    mask = np.array(Image.open(mask_path))
    overlay = img.copy()
    overlay[mask > 0] = [255, 0, 0]  # rojo sobre el tumor

    ax_row[0].imshow(img)
    ax_row[0].set_title('MRI original')
    ax_row[1].imshow(mask, cmap='gray')
    ax_row[1].set_title('Máscara')
    ax_row[2].imshow(overlay)
    ax_row[2].set_title('Superposición')
    for ax in ax_row:
        ax.axis('off')

# Elegir 3 muestras con tumor
tumor_indices = [i for i, m in enumerate(mask_paths)
                 if np.array(Image.open(m)).max() > 0][:3]

fig, axes = plt.subplots(3, 3, figsize=(12, 10))
for row, idx in enumerate(tumor_indices):
    show_sample(image_paths[idx], mask_paths[idx], axes[row])
plt.suptitle('Muestras del dataset (imágenes con tumor)', fontsize=14)
plt.tight_layout()
plt.show()

"""## 3. Preprocesamiento

Pasos aplicados:
- **Redimensionamiento:** todas las imágenes a 256×256 píxeles.
- **Normalización:** media y desvío estándar de ImageNet (ya que usamos backbone preentrenado).
- **División de datos:** 70 % entrenamiento / 15 % validación / 15 % test, estratificada por presencia de tumor.
- **Data augmentation** (solo en entrenamiento): flip horizontal/vertical, rotaciones aleatorias, ajuste de brillo/contraste.
"""

import torch
import torchvision.transforms.functional as TF
import random
from sklearn.model_selection import train_test_split

IMG_SIZE = 256
SEED     = 42

# Etiquetas para estratificación: 1 si hay tumor, 0 si no
labels = [1 if np.array(Image.open(m)).max() > 0 else 0 for m in mask_paths]

# Split 70 / 15 / 15
# El parámetro stratify=labels garantiza que la proporción de imágenes con tumor vs sin tumor se mantenga igual en los tres splits.
idx = list(range(len(image_paths)))
idx_train, idx_temp, y_train, y_temp = train_test_split(
    idx, labels, test_size=0.30, random_state=SEED, stratify=labels)
idx_val, idx_test, _, _ = train_test_split(
    idx_temp, y_temp, test_size=0.50, random_state=SEED, stratify=y_temp)

print(f'Entrenamiento: {len(idx_train)} | Validación: {len(idx_val)} | Test: {len(idx_test)}')
print(f'Tumor en train: {sum(y_train)}/{len(y_train)} '
      f'({100*sum(y_train)/len(y_train):.1f}%)')

"""## 4. Dataset y DataLoaders"""

from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T

MEAN = [0.485, 0.456, 0.406]
STD  = [0.229, 0.224, 0.225]

class BrainMRIDataset(Dataset):
    def __init__(self, indices, img_paths, mask_paths, augment=False):
        self.indices    = indices
        self.img_paths  = img_paths
        self.mask_paths = mask_paths
        self.augment    = augment
        self.normalize  = T.Normalize(mean=MEAN, std=STD)

    def __len__(self):
        return len(self.indices)

    def _augment(self, img, mask):
        # Flip horizontal
        if random.random() > 0.5:
            img  = TF.hflip(img)
            mask = TF.hflip(mask)
        # Flip vertical
        if random.random() > 0.5:
            img  = TF.vflip(img)
            mask = TF.vflip(mask)
        # Rotación aleatoria ±30°
        angle = random.uniform(-30, 30)
        img   = TF.rotate(img, angle)
        mask  = TF.rotate(mask, angle)
        # Brillo y contraste
        img = TF.adjust_brightness(img, random.uniform(0.8, 1.2))
        img = TF.adjust_contrast(img,   random.uniform(0.8, 1.2))
        return img, mask

    def __getitem__(self, item):
        idx  = self.indices[item]
        img  = Image.open(self.img_paths[idx]).convert('RGB').resize(
                   (IMG_SIZE, IMG_SIZE), Image.BILINEAR)
        mask = Image.open(self.mask_paths[idx]).convert('L').resize(
                   (IMG_SIZE, IMG_SIZE), Image.NEAREST)

        img  = TF.to_tensor(img)           # [3, H, W], float [0,1]
        mask = TF.to_tensor(mask)          # [1, H, W], float [0,1]
        mask = (mask > 0.5).float()

        if self.augment:
            img_pil  = TF.to_pil_image(img)
            mask_pil = TF.to_pil_image(mask)
            img_pil, mask_pil = self._augment(img_pil, mask_pil)
            img  = TF.to_tensor(img_pil)
            mask = TF.to_tensor(mask_pil)
            mask = (mask > 0.5).float()

        img = self.normalize(img)
        return img, mask


BATCH_SIZE = 16

train_ds = BrainMRIDataset(idx_train, image_paths, mask_paths, augment=True)
val_ds   = BrainMRIDataset(idx_val,   image_paths, mask_paths, augment=False)
test_ds  = BrainMRIDataset(idx_test,  image_paths, mask_paths, augment=False)

# shuffle = True está solo en train ya que mezcla los ejemplos en cada época para evitar que el modelo aprenda el orden
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f'Batches — train: {len(train_loader)} | val: {len(val_loader)} | test: {len(test_loader)}')

# Verificar un batch
imgs, masks = next(iter(train_loader))
print(f'Batch imágenes: {imgs.shape}, dtype: {imgs.dtype}')
print(f'Batch máscaras: {masks.shape}, valores únicos: {masks.unique().tolist()}')

# Desnormalizar para visualizar
def denorm(t):
    mean = torch.tensor(MEAN).view(3,1,1)
    std  = torch.tensor(STD).view(3,1,1)
    return (t * std + mean).clamp(0, 1)

fig, axes = plt.subplots(2, 4, figsize=(14, 6))
for i in range(4):
    axes[0, i].imshow(denorm(imgs[i]).permute(1,2,0))
    axes[0, i].set_title('Imagen (augmentada)')
    axes[1, i].imshow(masks[i, 0], cmap='gray')
    axes[1, i].set_title('Máscara')
    axes[0, i].axis('off')
    axes[1, i].axis('off')
plt.tight_layout()
plt.show()

"""## 5. Arquitectura U-Net

Implementación desde cero de la U-Net con las siguientes adaptaciones:
- **Padding** `same` para que las resoluciones coincidan sin necesidad de cropping. Basicamente se agregan píxeles de relleno (ceros) alrededor para que la salida tenga el mismo tamaño que la entrada.
- Batch **Normalization** después de cada convolución, lo que estabiliza el entrenamiento.
Input  →  Convolución  →  Batch Norm  →  ReLU  →  Output
- **Dropout** en el cuello de botella que es donde existe mayor riesgo de que el modelo memorice el dataset de entrenamiento. El Dropout fuerza a la red a no depender de ninguna neurona específica, mejorando la generalización.

```
Encoder (contracción):  3 → 64 → 128 → 256 → 512
Bottleneck:             512 → 1024
Decoder (expansión):    1024 → 512 → 256 → 128 → 64
Output:                 64 → 1  (sigmoid)
```
"""

import torch.nn as nn
import torch.nn.functional as F


class ConvBlock(nn.Module):
    """Dos convoluciones 3×3 con BN y ReLU."""
    def __init__(self, in_ch, out_ch, dropout=0.0):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),
        )

    def forward(self, x):
        return self.block(x)


class UNet(nn.Module):
    def __init__(self, in_channels=3, out_channels=1, features=[64, 128, 256, 512]):
        super().__init__()
        self.encoder = nn.ModuleList()
        self.decoder = nn.ModuleList()
        self.pool    = nn.MaxPool2d(2, 2)

        # Encoder
        ch = in_channels
        for f in features:
            self.encoder.append(ConvBlock(ch, f))
            ch = f

        # Bottleneck
        self.bottleneck = ConvBlock(features[-1], features[-1] * 2, dropout=0.3)

        # Decoder
        for f in reversed(features):
            self.decoder.append(
                nn.ConvTranspose2d(f * 2, f, kernel_size=2, stride=2)
            )
            self.decoder.append(ConvBlock(f * 2, f))

        self.final_conv = nn.Conv2d(features[0], out_channels, kernel_size=1)

    def forward(self, x):
        skip_connections = []

        # Encoder
        for enc in self.encoder:
            x = enc(x)
            skip_connections.append(x)
            x = self.pool(x)

        x = self.bottleneck(x)
        skip_connections = skip_connections[::-1]  # invertir

        # Decoder
        for i in range(0, len(self.decoder), 2):
            x    = self.decoder[i](x)                 # upsampling
            skip = skip_connections[i // 2]
            # Por si las dimensiones no coinciden exactamente
            if x.shape != skip.shape:
                x = F.interpolate(x, size=skip.shape[2:], mode='bilinear', align_corners=False)
            x = torch.cat([skip, x], dim=1)
            x = self.decoder[i + 1](x)               # conv block

        return self.final_conv(x)  # sin activación (BCEWithLogitsLoss)


# Verificar arquitectura
model_test = UNet()
dummy      = torch.randn(2, 3, 256, 256)
out        = model_test(dummy)
print(f'Input:  {dummy.shape}')
print(f'Output: {out.shape}')

total_params = sum(p.numel() for p in model_test.parameters())
print(f'Parámetros totales: {total_params:,}')

"""## 6. Entrenamiento

**Función de pérdida:** combinación de BCE + Dice Loss.  
La Dice Loss es especialmente útil en datasets con fuerte desbalance de clases (la mayoría de los píxeles son fondo).
- El **Dice score** e **IoU** (Intersection over Union) miden la superposición entre la máscara de tumor predicha y la real. La diferencia es que IoU penaliza más que Dice Score.

Al tratar con tumores, Dice Score suele ser la métrica preferida, porque es más estable cuando la región es chica.

$$\mathcal{L} = \text{BCE} + (1 - \text{Dice})$$
"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Dispositivo: {device}')


def dice_loss(pred_logits, target, smooth=1.0):
    pred = torch.sigmoid(pred_logits)
    pred   = pred.view(-1)
    target = target.view(-1)
    intersection = (pred * target).sum()
    return 1 - (2 * intersection + smooth) / (pred.sum() + target.sum() + smooth)


def combined_loss(pred_logits, target):
    bce  = F.binary_cross_entropy_with_logits(pred_logits, target)
    dice = dice_loss(pred_logits, target)
    return bce + dice


def dice_score(pred_logits, target, threshold=0.5, smooth=1.0):
    """Dice coefficient como métrica (no como loss)."""
    pred = (torch.sigmoid(pred_logits) > threshold).float()
    pred   = pred.view(-1)
    target = target.view(-1)
    intersection = (pred * target).sum()
    return ((2 * intersection + smooth) / (pred.sum() + target.sum() + smooth)).item()


def iou_score(pred_logits, target, threshold=0.5, smooth=1.0):
    pred = (torch.sigmoid(pred_logits) > threshold).float()
    pred   = pred.view(-1)
    target = target.view(-1)
    intersection = (pred * target).sum()
    union = pred.sum() + target.sum() - intersection
    return ((intersection + smooth) / (union + smooth)).item()

from google.colab import drive
drive.mount('/content/drive')

from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
import json

EPOCHS    = 30
LR        = 1e-4
PATIENCE  = 7

SAVE_PATH = '/content/drive/MyDrive/best_unet.pth'
HISTORY_PATH = '/content/drive/MyDrive/history.json'

model     = UNet().to(device)
optimizer = Adam(model.parameters(), lr=LR, weight_decay=1e-5)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)


def run_epoch(loader, train=True):
    model.train(train)
    total_loss, total_dice, total_iou = 0, 0, 0
    ctx = torch.enable_grad() if train else torch.no_grad()

    with ctx:
        for imgs, masks in loader:
            imgs, masks = imgs.to(device), masks.to(device)
            preds = model(imgs)
            loss  = combined_loss(preds, masks)

            if train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            total_loss += loss.item()
            total_dice += dice_score(preds, masks)
            total_iou  += iou_score(preds, masks)

    n = len(loader)
    return total_loss / n, total_dice / n, total_iou / n


#  CAMBIO: ahora guardamos IoU
history = {
    'train_loss': [], 'val_loss': [],
    'train_iou': [],  'val_iou': []
}

best_val_loss = float('inf')
patience_cnt  = 0


for epoch in range(1, EPOCHS + 1):
    tr_loss, _, tr_iou = run_epoch(train_loader, train=True)
    vl_loss, _, vl_iou = run_epoch(val_loader,   train=False)

    scheduler.step(vl_loss)

    history['train_loss'].append(tr_loss)
    history['val_loss'].append(vl_loss)
    history['train_iou'].append(tr_iou)
    history['val_iou'].append(vl_iou)

    print(f'Epoch [{epoch:02d}/{EPOCHS}]  '
          f'Loss → train: {tr_loss:.4f} | val: {vl_loss:.4f}  '
          f'IoU  → train: {tr_iou:.4f} | val: {vl_iou:.4f}')

    #  guardar mejor modelo en Drive
    if vl_loss < best_val_loss:
        best_val_loss = vl_loss
        patience_cnt  = 0
        torch.save(model.state_dict(), SAVE_PATH)
    else:
        patience_cnt += 1
        if patience_cnt >= PATIENCE:
            print(f'\nEarly stopping en epoch {epoch}.')
            break

    #  guardado progresivo (clave)
    with open(HISTORY_PATH, 'w') as f:
        json.dump(history, f)


print('\nEntrenamiento finalizado. Mejor val_loss:', best_val_loss)

# 🔥 cargar mejor modelo
model.load_state_dict(torch.load(SAVE_PATH, map_location=device))
model.eval()

from google.colab import drive
drive.mount('/content/drive')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# recrear modelo
model = UNet().to(device)

# cargar modelo entrenado
model.load_state_dict(torch.load('/content/drive/MyDrive/best_unet.pth', map_location=device))
model.eval()

import json

with open('/content/drive/MyDrive/history.json', 'r') as f:
    history = json.load(f)

# Curvas de entrenamiento
epochs_range = range(1, len(history['train_loss']) + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# LOSS
axes[0].plot(epochs_range, history['train_loss'], label='Train Loss')
axes[0].plot(epochs_range, history['val_loss'],   label='Val Loss')
axes[0].set_title('Función de pérdida')
axes[0].set_xlabel('Época')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(True)

#  IOU (nuevo)
axes[1].plot(epochs_range, history['train_iou'], label='Train IoU')
axes[1].plot(epochs_range, history['val_iou'],   label='Val IoU')
axes[1].set_title('IoU (Intersection over Union)')
axes[1].set_xlabel('Época')
axes[1].set_ylabel('IoU')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""## 7. Evaluación y resultados"""

import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = UNet().to(device)

model.load_state_dict(torch.load('/content/drive/MyDrive/best_unet.pth', map_location=device))
model.eval()

# Cargar el mejor modelo
model.load_state_dict(torch.load('/content/drive/MyDrive/best_unet.pth', map_location=device))
model.eval()

# Métricas finales en test
test_loss, test_dice, test_iou = run_epoch(test_loader, train=False)
print(f'=== Resultados en conjunto de TEST ===')
print(f'Loss:  {test_loss:.4f}')
print(f'Dice:  {test_dice:.4f}')
print(f'IoU:   {test_iou:.4f}')

# Visualización: predicción vs. máscara real en imágenes de test
def show_predictions(dataset, n=6):
    indices = random.sample(range(len(dataset)), n)
    fig, axes = plt.subplots(n, 3, figsize=(10, 4 * n))

    for row, i in enumerate(indices):
        img_t, mask_t = dataset[i]
        with torch.no_grad():
            pred_logit = model(img_t.unsqueeze(0).to(device))
        pred_mask = (torch.sigmoid(pred_logit).squeeze().cpu() > 0.5).float()

        img_vis = denorm(img_t).permute(1, 2, 0).numpy()

        axes[row, 0].imshow(img_vis)
        axes[row, 0].set_title('MRI')
        axes[row, 1].imshow(mask_t.squeeze(), cmap='gray')
        axes[row, 1].set_title('Máscara real')
        axes[row, 2].imshow(pred_mask, cmap='gray')
        axes[row, 2].set_title('Predicción')
        for ax in axes[row]:
            ax.axis('off')

    plt.suptitle('Predicciones del modelo sobre imágenes de test', fontsize=14)
    plt.tight_layout()
    plt.show()

show_predictions(test_ds, n=10)

def show_predictions_with_tumor(dataset, n=6):
    indices = []

    # 1. filtrar solo imágenes con tumor
    for i in range(len(dataset)):
        _, mask_t = dataset[i]
        if mask_t.max() > 0:  # hay tumor
            indices.append(i)

    # 2. samplear de esos
    indices = random.sample(indices, min(n, len(indices)))

    fig, axes = plt.subplots(len(indices), 3, figsize=(10, 4 * len(indices)))

    for row, i in enumerate(indices):
        img_t, mask_t = dataset[i]

        with torch.no_grad():
            pred_logit = model(img_t.unsqueeze(0).to(device))

        pred_mask = (torch.sigmoid(pred_logit).squeeze().cpu() > 0.5).float()
        img_vis = denorm(img_t).permute(1, 2, 0).numpy()

        axes[row, 0].imshow(img_vis)
        axes[row, 0].set_title('MRI')

        axes[row, 1].imshow(mask_t.squeeze(), cmap='gray')
        axes[row, 1].set_title('Máscara real')

        axes[row, 2].imshow(pred_mask, cmap='gray')
        axes[row, 2].set_title('Predicción')

        for ax in axes[row]:
            ax.axis('off')

    plt.suptitle('Predicciones (solo casos con tumor)', fontsize=14)
    plt.tight_layout()
    plt.show()

show_predictions_with_tumor(test_ds, n=10)

# Comparación visual con superposición de colores
# Verde = verdadero positivo, Rojo = falso positivo, Azul = falso negativo
def show_overlap(dataset, n=4):
    indices = random.sample(range(len(dataset)), n)
    fig, axes = plt.subplots(1, n, figsize=(4 * n, 4))

    for col, i in enumerate(indices):
        img_t, mask_t = dataset[i]
        with torch.no_grad():
            pred = (torch.sigmoid(model(img_t.unsqueeze(0).to(device))).squeeze().cpu() > 0.5).numpy()
        gt   = mask_t.squeeze().numpy().astype(bool)
        pred = pred.astype(bool)

        img_vis = denorm(img_t).permute(1, 2, 0).numpy().copy()
        img_vis[gt  & pred]  = [0, 1, 0]   # TP — verde
        img_vis[~gt & pred]  = [1, 0, 0]   # FP — rojo
        img_vis[gt  & ~pred] = [0, 0, 1]   # FN — azul

        axes[col].imshow(img_vis)
        axes[col].set_title('Verde=TP  Rojo=FP  Azul=FN')
        axes[col].axis('off')

    plt.suptitle('Análisis de errores del modelo', fontsize=13)
    plt.tight_layout()
    plt.show()

show_overlap(test_ds, n=4)

def show_worst_predictions(dataset, n=6):
    scores = []

    # 1. calcular IoU para todo el dataset
    for i in range(len(dataset)):
        img_t, mask_t = dataset[i]

        with torch.no_grad():
            pred_logit = model(img_t.unsqueeze(0).to(device))

        iou = iou_score(pred_logit, mask_t.unsqueeze(0).to(device))
        scores.append((i, iou))

    # 2. ordenar por peor IoU
    scores = sorted(scores, key=lambda x: x[1])[:n]

    fig, axes = plt.subplots(n, 3, figsize=(10, 4 * n))

    for row, (i, iou) in enumerate(scores):
        img_t, mask_t = dataset[i]

        with torch.no_grad():
            pred_logit = model(img_t.unsqueeze(0).to(device))

        pred_mask = (torch.sigmoid(pred_logit).squeeze().cpu() > 0.5).float()
        img_vis = denorm(img_t).permute(1, 2, 0).numpy()

        axes[row, 0].imshow(img_vis)
        axes[row, 0].set_title('MRI')

        axes[row, 1].imshow(mask_t.squeeze(), cmap='gray')
        axes[row, 1].set_title('Máscara real')

        axes[row, 2].imshow(pred_mask, cmap='gray')
        axes[row, 2].set_title(f'Predicción\nIoU={iou:.3f}')

        for ax in axes[row]:
            ax.axis('off')

    plt.suptitle('Peores predicciones del modelo (menor IoU)', fontsize=14)
    plt.tight_layout()
    plt.show()

show_worst_predictions(test_ds, n=3)

"""Se observó que el modelo tiende a asociar regiones de alta intensidad (zonas más brillantes en la imagen) con la presencia de tumor. Esto provoca falsos positivos en imágenes donde no hay tumor, pero sí estructuras o variaciones de intensidad que el modelo interpreta erróneamente como tales.

## Discusión

### Resultados obtenidos
- **Dice en test:** 0.8657
- **IoU en test:** 0.7683

### Análisis
El dataset tiene un fuerte **desbalance de clases** ya que la mayor parte de las imágenes no contienen tumor visible, y en las que sí lo contienen, los tumores representan una fracción pequeña del total de píxeles.
"""